// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           28
// Async Callback (empty):               1
// Total number of exported functions:  30

#![no_std]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    lending_pool
    (
        enter_market
        exit_market
        addCollateral
        removeCollateral
        borrow
        repay
        liquidate
        updateCollateralWithInterest
        updateBorrowsWithDebt
        getLiqPoolTemplateAddress
        createLiquidityPool
        upgradeLiquidityPool
        setAggregator
        setAssetLoanToValue
        setAssetLiquidationBonus
        getPoolAddress
        getPoolAllowed
        getAssetLoanToValue
        getAssetLiquidationBonus
        getAccountToken
        getAccountPositions
        getDepositPositions
        getBorrowPositions
        getCollateralAmountForToken
        getTotalCollateralAvailable
        getTotalBorrowInDollars
        setPriceAggregatorAddress
        getAggregatorAddress
    )
}

multiversx_sc_wasm_adapter::empty_callback! {}
