// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           27
// Async Callback (empty):               1
// Total number of exported functions:  29

#![no_std]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    liquidity_pool
    (
        getPoolAsset
        getReserves
        getRewardsReserves
        getLendToken
        borrowToken
        getPoolParams
        getTotalBorrow
        getLiquidationThreshold
        getBorrowIndex
        getSupplyIndex
        borrowIndexLastUpdateRound
        getAccountToken
        getAccountPositions
        updateCollateralWithInterest
        updateBorrowsWithDebt
        addCollateral
        borrow
        remove_collateral
        repay
        sendTokens
        getCapitalUtilisation
        getTotalSuppliedCapital
        getDebtInterest
        getDepositRate
        getBorrowRate
        setPriceAggregatorAddress
        getAggregatorAddress
    )
}

multiversx_sc_wasm_adapter::empty_callback! {}
